site_name: Documentation
theme:
  name: material
  logo: _static/logo-white.png
  favicon: _static/ico_white.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - navigation.indexes
    - content.code.annotate
  palette:
    primary: indigo
    accent: indigo
  custom_dir: overrides
  static_templates:
    - 404.html
  

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/dfir_iris
    - icon: fontawesome/brands/github 
      link: https://github.com/dfir-iris
    - icon: fontawesome/solid/paper-plane
      link: mailto:<contact@dfir-iris.org>
    - icon: material/discord
      link: https://discord.gg/76tM6QUJza

repo_url: https://github.com/dfir-iris/iris-web
site_url: https://dfir-iris.github.io
site_description: "DFIR-IRIS Documentation - An incident response collaborative platform"
site_author: "DFIR-IRIS Team"

repo_name: DFIR-IRIS Web
edit_uri: ""

copyright: Copyright &copy; 2021-2022 - DFIR-IRIS Team

plugins:
  - git-revision-date
  - search
  - awesome-pages

dev_addr: '127.0.0.1:8080'

